# Generated by Django 3.1.4 on 2022-12-05 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lotteries", "0002_winningballot"),
    ]

    operations = [
        migrations.AddField(
            model_name="lotterygame",
            name="game_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
