version: '3.8'

services:
  db:
    container_name: django_admin_db
    image: postgres
    restart: always
    user: root
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  web:
    container_name: django_api
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 5; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis
  celery-beat:
    build: .
    command: celery -A core beat -l info
    volumes:
      - .:/code
    depends_on:
      - redis